In [2]:
# your own linear regression build with python code

In [3]:
import pandas as pd

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(r'diabetes.csv')

In [6]:
df

patient_number  cholesterol  glucose  hdl_chol chol_hdl_ratio  age  \
0                 1          193       77        49            3,9   19   
1                 2          146       79        41            3,6   19   
2                 3          217       75        54              4   20   
3                 4          226       97        70            3,2   20   
4                 5          164       91        67            2,4   20   
..              ...          ...      ...       ...            ...  ...   
385             386          227      105        44            5,2   83   
386             387          226      279        52            4,3   84   
387             388          301       90       118            2,6   89   
388             389          232      184       114              2   91   
389             390          165       94        69            2,4   92   

     gender  height  weight   bmi  systolic_bp  diastolic_bp  waist  hip  \
0    female      61     119  22,5          118            70     32   38   
1    female      60     135  26,4          108            58     33   40   
2    female      67     187  29,3          110            72     40   45   
3    female      64     114  19,6          122            64     31   39   
4    female      70     141  20,2          122            86     32   39   
..      ...     ...     ...   ...          ...           ...    ...  ...   
385  female      59     125  25,2          150            90     35   40   
386  female      60     192  37,5          144            88     41   48   
387  female      61     115  21,7          218            90     31   41   
388  female      61     127    24          170            82     35   38   
389  female      62     217  39,7          160            82     51   51   

    waist_hip_ratio     diabetes  
0              0,84  No diabetes  
1              0,83  No diabetes  
2              0,89  No diabetes  
3              0,79  No diabetes  
4              0,82  No diabetes  
..              ...          ...  
385            0,88  No diabetes  
386            0,85     Diabetes  
387            0,76  No diabetes  
388            0,92     Diabetes  
389               1  No diabetes  

[390 rows x 16 columns]

In [8]:
x = df['weight'].values.reshape(-1,1)
y = df['hip'].values.reshape(-1,1)

In [9]:
x

array([[119],
       [135],
       [187],
       [114],
       [141],
       [161],
       [115],
       [145],
       [159],
       [170],
       [187],
       [274],
       [169],
       [142],
       [155],
       [158],
       [163],
       [220],
       [114],
       [148],
       [223],
       [137],
       [160],
       [235],
       [277],
       [185],
       [180],
       [183],
       [164],
       [245],
       [113],
       [118],
       [245],
       [154],
       [162],
       [174],
       [174],
       [130],
       [227],
       [259],
       [150],
       [119],
       [145],
       [170],
       [210],
       [209],
       [289],
       [185],
       [141],
       [179],
       [180],
       [204],
       [130],
       [154],
       [200],
       [126],
       [200],
       [225],
       [170],
       [123],
       [ 99],
       [120],
       [218],
       [180],
       [167],
       [142],
       [143],
       [257],
       [165],
       [125],
       [165],
      

In [10]:
y

array([[38],
       [40],
       [45],
       [39],
       [39],
       [40],
       [37],
       [36],
       [39],
       [46],
       [41],
       [58],
       [43],
       [39],
       [39],
       [43],
       [39],
       [52],
       [35],
       [38],
       [50],
       [35],
       [40],
       [50],
       [49],
       [47],
       [41],
       [45],
       [40],
       [47],
       [38],
       [34],
       [58],
       [42],
       [39],
       [46],
       [35],
       [40],
       [44],
       [49],
       [39],
       [37],
       [35],
       [41],
       [47],
       [43],
       [51],
       [44],
       [38],
       [42],
       [43],
       [41],
       [35],
       [38],
       [46],
       [32],
       [45],
       [52],
       [39],
       [37],
       [36],
       [38],
       [48],
       [42],
       [40],
       [34],
       [40],
       [55],
       [38],
       [39],
       [42],
       [49],
       [41],
       [51],
       [47],
       [42],
       [40],

In [11]:
#now build own linearRegresson model with python

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20)

In [35]:
class yourmodel:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,xtrain,ytrain):
        num =0
        den = 0
        
        for i in range(xtrain.shape[0]):
            #now calculate m value formula = (xi - xmean) (yi - ymean)
                                                    #-------------------------
                                                     # (xi - xmean)2
                    #first (xi - xmean) - (yi - y mean)
                    
                num = num + ((xtrain[i] - xtrain.mean()) * (ytrain[i] - ytrain.mean()))
                 #first (xi - xmean) - (yi - y mean)
                    
           
                    # send (xi - xmean)2
                    
                den =  den + ((xtrain[i] - xtrain.mean()) * (xtrain[i] - xtrain.mean()))
            
        self.m = num/den
        #now calculate  b
        # b =  y(mean)- m xmean
        
        self.b = ytrain.mean() - (self.m * xtrain.mean())
        
        print("coef",self.m)
        print("intercept",self.b)
            
    def predict(self,xtest):
          # y = mx + b 
        print(xtest)
        return self.m * xtest +self.b
            
        # complete your model now fit and predict tha model

In [36]:
lr  = yourmodel()

In [37]:
lr

In [38]:
#now fit tha model
lr.fit(xtrain,ytrain)

coef [0.11624112]
intercept [22.4199573]


In [39]:
#this your m,b values

In [40]:
# now predict the model

In [41]:
lr.predict(xtest)

[[127]
 [180]
 [145]
 [251]
 [142]
 [215]
 [204]
 [174]
 [198]
 [192]
 [290]
 [159]
 [181]
 [183]
 [141]
 [186]
 [147]
 [262]
 [158]
 [167]
 [217]
 [136]
 [200]
 [183]
 [123]
 [182]
 [125]
 [154]
 [191]
 [190]
 [186]
 [189]
 [169]
 [169]
 [223]
 [162]
 [140]
 [181]
 [205]
 [200]
 [156]
 [187]
 [167]
 [118]
 [169]
 [145]
 [135]
 [144]
 [144]
 [175]
 [189]
 [139]
 [ 99]
 [172]
 [200]
 [140]
 [170]
 [235]
 [200]
 [212]
 [159]
 [159]
 [212]
 [167]
 [175]
 [182]
 [163]
 [224]
 [180]
 [205]
 [282]
 [183]
 [191]
 [118]
 [259]
 [197]
 [227]
 [136]]


array([[37.18257992],
       [43.34335944],
       [39.27492013],
       [51.59647917],
       [38.92619677],
       [47.41179875],
       [46.13314639],
       [42.6459127 ],
       [45.43569965],
       [44.73825292],
       [56.12988297],
       [40.90229586],
       [43.45960056],
       [43.69208281],
       [38.80995564],
       [44.04080618],
       [39.50740238],
       [52.87513153],
       [40.78605473],
       [41.83222484],
       [47.64428099],
       [38.22875003],
       [45.6681819 ],
       [43.69208281],
       [36.71761543],
       [43.57584169],
       [36.95009767],
       [40.32109024],
       [44.62201179],
       [44.50577067],
       [44.04080618],
       [44.38952955],
       [42.06470709],
       [42.06470709],
       [48.34172773],
       [41.25101923],
       [38.69371452],
       [43.45960056],
       [46.24938752],
       [45.6681819 ],
       [40.55357249],
       [44.1570473 ],
       [41.83222484],
       [36.13640981],
       [42.06470709],
       [39

In [42]:
#now check with compare the sklearn model and your model

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
l = LinearRegression()


In [45]:
l.fit(xtrain,ytrain)

LinearRegression()

In [46]:
#now 2 model ,1.is your model,2.sklearn model compare

In [47]:
lr

In [48]:
l

LinearRegression()

In [54]:
#this one your model
lr.predict([xtest[0]])

[array([127], dtype=int64)]


array([[37.18257992]])

In [56]:
# this one sklearn model 
l.predict([xtest[0]])

array([[37.18257992]])

In [53]:
xtest[0]

array([127], dtype=int64)

In [52]:
ytest[0]

array([38], dtype=int64)

In [57]:
# 2 model is same prediction

In [58]:
#m,b value sklearn and your model

In [59]:
l.coef_

array([[0.11624112]])

In [60]:
l.intercept_

array([22.4199573])

In [61]:
lr.fit(xtrain,ytrain)# your model

coef [0.11624112]
intercept [22.4199573]


In [62]:
# your model and sklearn model bath are same good work 