In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'diabetes.csv')

In [4]:
df

patient_number  cholesterol  glucose  hdl_chol chol_hdl_ratio  age  \
0                 1          193       77        49            3,9   19   
1                 2          146       79        41            3,6   19   
2                 3          217       75        54              4   20   
3                 4          226       97        70            3,2   20   
4                 5          164       91        67            2,4   20   
..              ...          ...      ...       ...            ...  ...   
385             386          227      105        44            5,2   83   
386             387          226      279        52            4,3   84   
387             388          301       90       118            2,6   89   
388             389          232      184       114              2   91   
389             390          165       94        69            2,4   92   

     gender  height  weight   bmi  systolic_bp  diastolic_bp  waist  hip  \
0    female      61     119  22,5          118            70     32   38   
1    female      60     135  26,4          108            58     33   40   
2    female      67     187  29,3          110            72     40   45   
3    female      64     114  19,6          122            64     31   39   
4    female      70     141  20,2          122            86     32   39   
..      ...     ...     ...   ...          ...           ...    ...  ...   
385  female      59     125  25,2          150            90     35   40   
386  female      60     192  37,5          144            88     41   48   
387  female      61     115  21,7          218            90     31   41   
388  female      61     127    24          170            82     35   38   
389  female      62     217  39,7          160            82     51   51   

    waist_hip_ratio     diabetes  
0              0,84  No diabetes  
1              0,83  No diabetes  
2              0,89  No diabetes  
3              0,79  No diabetes  
4              0,82  No diabetes  
..              ...          ...  
385            0,88  No diabetes  
386            0,85     Diabetes  
387            0,76  No diabetes  
388            0,92     Diabetes  
389               1  No diabetes  

[390 rows x 16 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [9]:
x = df['weight'].values.reshape(-1,1)
y = df['hip'].values.reshape(-1,1)

In [11]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.20)

In [85]:
lr = LinearRegression()


In [86]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [87]:
lr.intercept_

array([22.92706485])

In [91]:
lr.coef_

array([[0.11211215]])

In [100]:
lr.predict([[255]])

array([[51.51566277]])

In [105]:
class yourregression:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,xtrain,ytrain):
        num =0
        den = 0
        
        for i in range(xtrain.shape[0]):
            #now calculate m value formula = (xi - xmean) (yi - ymean)
                                                    #-------------------------
                                                     # (xi - xmean)2
                    #first (xi - xmean) - (yi - y mean)
                    
                num = num + ((xtrain[i] - xtrain.mean()) * (ytrain[i] - ytrain.mean()))
                 #first (xi - xmean) - (yi - y mean)
                    
           
                    # send (xi - xmean)2
                    
                den =  den + ((xtrain[i] - xtrain.mean()) * (xtrain[i] - xtrain.mean()))
            
        self.m = num/den
        #now calculate  b
        # b =  y(mean)- m xmean
        
        self.b = ytrain.mean() - (self.m * xtrain.mean())
        
        print("coef",self.m)
        print("intercept",self.b)
            
    def predict(self,xtest):
          # y = mx + b 
        print(xtest)
        return self.m * xtest +self.b
            
        
    
    

In [93]:
li = yourregression()

In [94]:
li.fit(xtrain,ytrain)

coef [0.11211215]
intercept [22.92706485]


In [104]:
li.predict(255)

255


array([51.51566277])

In [68]:
((xtrain[0] - xtrain.mean()) * (ytrain[0] - ytrain.mean()))
    

array([82.86612426])

In [23]:
xtrain.shape[0]

312

In [95]:
xtest

array([[255],
       [174],
       [167],
       [187],
       [210],
       [125],
       [163],
       [172],
       [159],
       [277],
       [190],
       [145],
       [288],
       [222],
       [155],
       [225],
       [145],
       [189],
       [228],
       [165],
       [130],
       [183],
       [205],
       [180],
       [123],
       [185],
       [182],
       [179],
       [134],
       [212],
       [224],
       [189],
       [197],
       [114],
       [119],
       [160],
       [200],
       [170],
       [179],
       [181],
       [170],
       [219],
       [244],
       [115],
       [237],
       [173],
       [165],
       [152],
       [160],
       [179],
       [205],
       [159],
       [239],
       [181],
       [120],
       [118],
       [169],
       [201],
       [145],
       [179],
       [178],
       [142],
       [290],
       [169],
       [157],
       [179],
       [145],
       [219],
       [163],
       [166],
       [154],
      

In [96]:
ytest

array([[52],
       [44],
       [39],
       [37],
       [53],
       [40],
       [43],
       [43],
       [35],
       [49],
       [42],
       [37],
       [55],
       [51],
       [41],
       [52],
       [35],
       [39],
       [54],
       [45],
       [35],
       [43],
       [49],
       [44],
       [41],
       [47],
       [39],
       [45],
       [40],
       [44],
       [50],
       [46],
       [48],
       [39],
       [38],
       [45],
       [45],
       [46],
       [47],
       [46],
       [40],
       [42],
       [51],
       [37],
       [56],
       [40],
       [42],
       [38],
       [45],
       [44],
       [41],
       [41],
       [53],
       [49],
       [40],
       [34],
       [44],
       [49],
       [42],
       [48],
       [41],
       [35],
       [62],
       [41],
       [41],
       [42],
       [42],
       [52],
       [38],
       [40],
       [41],
       [38],
       [54],
       [50],
       [32],
       [54],
       [44],